### ISSUE TITLE
[PROD] User registration fails due to frontend_url env variable import

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#1403]
A frontend_url gaining step failed here. If possible, let's fix it:
```
==> /home/ifrc/logs/user_registration_reminder.log <==
Traceback (most recent call last):
  File "/home/ifrc/go-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ifrc/go-api/api/management/commands/user_registration_reminder.py", line 17, in <module>
    from main.frontend import frontend_url
ImportError: cannot import name 'frontend_url' from 'main.frontend' (/home/ifrc/go-api/main/frontend.py)
```

**Comment by thenav56** [comment]
We need to define a module for a related frontend URL in main/frontend.py and replace that with frontend_url.

For eg:
```
def get_project_url(id):
    return f'https://{settings.FRONTEND_URL}/three-w/{id}/'
```

**Comment by szabozoltan69** [comment]
This import (which gave the error) was not used in this code, so I removed.
Or do you mean this suggestion for other code parts?

**Comment by thenav56** [comment]
Yeah, for the replacement for `from main.frontend import frontend_url` where this is used.
