### ISSUE TITLE
PROD: Flash update notification emails are not sent

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1547]
Sharing Flash updates to Donors and Donor groups are not sent on Prod:
![image](https://user-images.githubusercontent.com/68283148/194060364-84278d7f-4374-49ed-837a-15171f91235f.png)

Use the Share button and select Internal Admin donor group to share:
https://go.ifrc.org/flash-update/6/

It works on STAG:
![image](https://user-images.githubusercontent.com/68283148/194060174-1dd43fe9-b1c4-4e03-8efa-8099d80d59d9.png)

https://go-stage.ifrc.org/flash-update/26/

**Comment by szabozoltan69** [comment]
On PROD I can see this in the docker log of celery-default:

```
[2022-10-05 11:41:43,599: INFO/MainProcess] Task flash_update.tasks.share_flash_update[4afedc34-c061-43fb-a3c3-eb533ead4b83] received
[2022-10-05 11:41:43,848: ERROR/ForkPoolWorker-1] Task flash_update.tasks.share_flash_update[4afedc34-c061-43fb-a3c3-eb533ead4b83] raised unexpected: TypeError('sequence item 0: expected str instance, set found')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ifrc/go-api/flash_update/tasks.py", line 37, in share_flash_update
    send_notification(
  File "/home/ifrc/go-api/notifications/notification.py", line 109, in send_notification
    recipients_as_string = ','.join(to_addresses)
TypeError: sequence item 0: expected str instance, set found
```

To compare with the Staging site log:
```
[2022-10-05 11:43:45,080: INFO/ForkPoolWorker-1] Client-Request-ID=f7c7a77c-44a2-11ed-9851-0242ac140004 Outgoing request: Method=PUT, Path=/logs/go.log.2022-10-05_08-35, Query={'timeout': None}, Headers={'x-ms-blob-type': 'BlockBlob', 'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-blob-cache-control': None, 'x-ms-blob-content-type': 'text/plain', 'x-ms-blob-content-disposition': None, 'x-ms-blob-content-md5': None, 'x-ms-blob-content-encoding': None, 'x-ms-blob-content-language': None, 'Content-Length': '698', 'x-ms-version': '2018-03-28', 'User-Agent': 'Azure-Storage/1.4.0-1.5.0 (Python CPython 3.8.12; Linux 4.15.0-1113-azure)', 'x-ms-client-request-id': 'f7c7a77c-44a2-11ed-9851-0242ac140004', 'x-ms-date': 'Wed, 05 Oct 2022 11:43:45 GMT', 'Authorization': 'REDACTED'}.
[2022-10-05 11:43:45,118: INFO/ForkPoolWorker-1] Client-Request-ID=f7c7a77c-44a2-11ed-9851-0242ac140004 Receiving Response: Server-Timestamp=Wed, 05 Oct 2022 11:43:44 GMT, Server-Request-ID=8b77b33d-701e-0123-1caf-d81f48000000, HTTP Status Code=201, Message=Created, Headers={'content-length': '0', 'content-md5': 'vF4oawiq6VwThCEK5OTEPg==', 'last-modified': 'Wed, 05 Oct 2022 11:43:45 GMT', 'etag': '"0x8DAA6C6DC00F6EC"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '8b77b33d-701e-0123-1caf-d81f48000000', 'x-ms-version': '2018-03-28', 'x-ms-request-server-encrypted': 'true', 'date': 'Wed, 05 Oct 2022 11:43:44 GMT'}.
[2022-10-05 11:43:45,079: INFO/ForkPoolWorker-1] Using test email addresses...
2022-10-05 11:43:45 INFO     []
[2022-10-05 11:43:45,119: INFO/ForkPoolWorker-1] []
2022-10-05 11:43:53 INFO     Subject: Flash Update: Pakistan - Flood  09/2022, Recipients: tovari@gmail.com
2022-10-05 11:43:53 INFO     GUID: f2a25772-a1ab-4243-b9a6-6b407998030c
[2022-10-05 11:43:53,070: INFO/ForkPoolWorker-1] Subject: Flash Update: Pakistan - Flood  09/2022, Recipients: tovari@gmail.com
[2022-10-05 11:43:53,071: INFO/ForkPoolWorker-1] GUID: f2a25772-a1ab-4243-b9a6-6b407998030c
2022-10-05 11:43:53 INFO     E-mails were sent successfully.
[2022-10-05 11:43:53,112: INFO/ForkPoolWorker-1] E-mails were sent successfully.
[2022-10-05 11:43:53,115: INFO/ForkPoolWorker-1] Task flash_update.tasks.share_flash_update[c00d3e7d-d5e7-4d9d-80a6-10c6e1bd1ef7] succeeded in 8.892887860536575s: {'resource_url': 'https://go-stage.ifrc.org/flash-update/26/', 'title': 'Pakistan - Flood  09/2022', 'situational_overview': '<p>admin1 update check, if all 4 selected admin remains in the report</p>', 'map_list': [], 'graphic_list': [], 'actions_taken': [{'organization': 'GOV', 'organization_display': 'Government', 'actions': [...], 'action_details': [...], 'summary': None, 'id': 392, 'client_id': None}, {'organization': 'FDRN', 'organization_display': 'Federation', 'actions': [...], 'action_details': [...], 'summary': None, 'id': 391, 'client_id': None}, {'organization': 'PNS', 'organization_display': 'RCRC', 'actions': [...], 'action_details': [...], 'summary': None, 'id': 390, 'client_id': None}, {'organization': 'NTLS', 'organization_display': 'National Society', 'actions': [...], 'action_details': [...], 'summary': None, 'id': 389, 'client_id': None}], 'resources': []}
```

**Comment by szabozoltan69** [comment]
I think the solution means this fix; instead of
```
    users_emails = set([*donors_emails, *donor_groups_emails])
```
let's use
```
    users_emails = list(set([*donors_emails, *donor_groups_emails]))
```

**Comment by szabozoltan69** [comment]
Maybe we could introduce here (for flash updates) also, which is [done for DREF notification](https://github.com/IFRCGo/go-api/pull/1546);
if a user already received an email, in case of editing+saving the document no more notifications are wanted.
