### ISSUE TITLE
Errors in ingest_gdacs.log and inggest_mdb.log

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#317]
There are some strange errors in **ingest_gdacs.log** and **inggest_mdb.log**.

gdacs: ValueError: invalid literal for int() with base 10: '1.78228028098837'
See below.

mdb is simple to solve: TypeError: object of type 'int' has no len()
(We should use simply processed_users instead of len(processed_users).)

**Comment by szabozoltan69** [comment]
Error log of gdacs issue:
```
Traceback (most recent call last):
  File "/home/ifrc/go-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/ifrc/go-api/api/management/commands/ingest_gdacs.py", line 63, in handle
    gdacsevent, created = GDACSEvent.objects.get_or_create(eventid=eid, defaults=data)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 489, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 521, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 417, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1284, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1237, in as_sql
    for obj in self.query.objs
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1237, in <listcomp>
    for obj in self.query.objs
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1236, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1176, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 767, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 762, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1826, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1.78228028098837'
```

**Comment by szabozoltan69** [comment]
Solved with image 1.1.11. (https://github.com/IFRCGo/go-api/pull/318),

**Comment by szabozoltan69** [comment]
There are again some errors in ingest_mdb.log:
 Country matching query does not exist

**Comment by szabozoltan69** [comment]
```2019-01-07 11:30:04 INFO     Attempting connection to FTP
2019-01-07 11:30:09 INFO     9111 reports in database
2019-01-07 11:30:10 INFO     0 reports created
2019-01-07 11:30:10 INFO     11490 reports in database
Traceback (most recent call last):
  File "/home/ifrc/go-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/ifrc/go-api/api/management/commands/ingest_mdb.py", line 366, in handle
    user.profile.country = Country.objects.get(pk=user_data['CountryID'])
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
api.models.DoesNotExist: Country matching query does not exist.```

**Comment by szabozoltan69** [comment]
This issue concerns to deleted country ids/names, in this case:
275,Hong Kong (China)
So we should put a conversion here if we receive an obsolete (or non-wanted) ID then let's use another one...
