### ISSUE TITLE
index_and_notify error in case of not having "modified_at"

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#364]
In production the index_and_notify job gives this error sometimes:
```
2019-03-23 16:40:04 INFO     Notifying 137 subscriber(s) about 1 modified event
2019-03-23 16:40:04 INFO     Indexing 0 updated field reports
2019-03-23 16:40:04 INFO     Indexing 0 updated appeals
2019-03-23 16:40:04 INFO     Indexing 1 updated events
2019-03-23 16:40:05 INFO     Notifications sent!
Traceback (most recent call last):
  File "/home/ifrc/go-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/ifrc/go-api/api/management/commands/index_and_notify.py", line 234, in handle
    self.index_updated_records(self.filter_just_created(updated_events))
  File "/home/ifrc/go-api/api/management/commands/index_and_notify.py", line 200, in filter_just_created
    if queryset.first().modified_at is not None:
AttributeError: 'Event' object has no attribute 'modified_at'
```

Maybe https://github.com/IFRCGo/go-api/blob/master/api/management/commands/index_and_notify.py#L200 should be changed to:
```
if hasattr(queryset.first(), 'modified_at') and queryset.first().modified_at is not None:
```
...because only the "not None" is not working in case when there is no "modified_at" attribute (e.g. in case of events and field_reports).

**Comment by szabozoltan69** [comment]
(This can be the root cause of https://github.com/IFRCGo/go-api/issues/362 ? )
